### ISSUE TITLE
Event playlist stream

### ISSUE THREAD

**Issue by advplyr** [devfviak/node-hls-server#2]
Thanks for sharing this package.

I am wondering if you have you used this with `-hls_playlist_type event` or do any live streaming.

When I am using the event playlist type for a movie, and begin playing the movie while it is still transcoding, I am unable to figure out how to have the HLS.js video player show the full movie duration.

**Comment by pedrio-gh** [comment]
Hi ! 
I haven't tried `-hls_playlist_type event`. I will take a look when I find some spare time

**Comment by advplyr** [comment]
What I don't understand with `hls_playlist_type vod` is that the `.m3u8` file is not created until the entire video is encoded.

Edit: I understand now, streaming services are generating the `.m3u8` file manually on the fly. So when the client requests a segment they first check that it exists, and restart the transcode if not.
